### ISSUE TITLE
using re.search() instead of re.fullmatch()

### ISSUE THREAD

**Issue by nusenu** [erans/torcontactinfoparser#11]
The valid_chars regex for the proof field is: `[adinrsu-]+`

The [proof](https://nusenu.github.io/ContactInfo-Information-Sharing-Specification/#proof) field accepts two values:

* uri-rsa
* dns-rsa

but when you supply `uri+rsa` the parser fails to return None and returns  `uri+rsa` instead, which is unexpected.

https://metrics.torproject.org/rs.html#details/759FC58B1CE2655028B2993F360AA7DB6741BA05

Example string:
```
email:tor+bridges[]bismuth.it url:https://bismuth.it proof:uri+rsa pgp:BECD152B6BAA1FA0FB5E00EF42C5CC9D07DF3288 ciissversion:2
```

The root cause appears to be here:

https://github.com/erans/torcontactinfoparser/blob/4823b1a1ca8f8625d34da7a4659725b5b73b8b2b/torcontactinfo.py#L52

Which uses `re.search()` instead of `re.fullmatch()`?

Do you happen to know why search() is used there?

**Comment by erans** [comment]
Don't really remember why its search and not fullmatch. I will check if fullmatch will fix it.

**Comment by erans** [comment]
Fixed.
