### ISSUE TITLE
use first, not last field when used multiple times

### ISSUE THREAD

**Issue by nusenu** [erans/torcontactinfoparser#3]
the spec says:

https://github.com/nusenu/ContactInfo-Information-Sharing-Specification#defined-fields
> A field identifier (key) MUST only be used once, if it appears multiple times in the ContactInfo string only the first occurance is considered.

the current code uses the last 
```
ciissversion:2 url:example.com url:example2.com
```
result: url=example2.com but it should be example.com

**Comment by nusenu** [comment]
moved to https://github.com/nusenu/torcontactinfoparser/issues/2

**Comment by erans** [comment]
Fixed and add a test (now this repo has pytest) to make sure it always conforms. Will add more tests later.
