### ISSUE TITLE
email value is not validated

### ISSUE THREAD

**Issue by nusenu** [erans/torcontactinfoparser#7]
We do validate all fields against a min/max length and valid chars but we lack
such checks on the email value.

We should incorporate an email adress validator that makes sure that the provided value is syntactically a valid email address.

**Comment by erans** [comment]
Usually email checks are kinda tricky. We can do the basic things, meaning, it should have some minimum length that is reasonable and have at least one "@" character and at least one "." character. Wdyt?

**Comment by nusenu** [comment]
can we simply reuse some library that does it?
https://github.com/JoshData/python-email-validator

**Comment by erans** [comment]
Ok, I found a reasonable regex to validate emails in a reasonable way and added some tests.

**Comment by erans** [comment]
This is a much heavier check including checking that the email domain is
valid. Do we want to use that instead of just checking that the email looks
ok?

**Comment by nusenu** [comment]
the DNS check is optional, but lets go with your regex for now until we run into internationalization issues.

I did run it and noticed it troughs an exception even though `raise_exception_on_invalid_value=False`
If the email is invalid it should not include the email field in the output.

**Comment by erans** [comment]
ok, will change that then.

**Comment by erans** [comment]
Will remove the exception. It will just return a null email if it's not
valid as if it's not there.

**Comment by nusenu** [comment]
I was wondering what is the general best practice for parsers.
Return the field with `None` content or do not return the field in the output at all?

I would benefit from a functionality that does not include it in the field name, but adds all fields that failed to pass validation into a special output field `{"failed_validation_fields": {"fieldname": "content", ..}}`

to clarify: that failed_validation_fields does not include strings that are no fieldnames at all.

**Comment by erans** [comment]
It really depends on how we want to handle that.

Some want to process it all and return a set of errors. Some want to stop
on the first issue.

We can probably add a "failedValidationFields" in the result and have an
array of all failed fields, since we don't provide a lot of details as to
why these fields have failed.

I'm good either way.
