### ISSUE TITLE
make email deobfuscation configurable

### ISSUE THREAD

**Issue by nusenu** [erans/torcontactinfoparser#8]
I use the output for a page similar to relay search.
therefore I want to retain the use of [] instead of @.

It would be nice if parse() would take an optional parameter `deobfuscate_email=False`

False return as is
True return [] replaced with @

**Comment by erans** [comment]
Added.

**Comment by nusenu** [comment]
thanks!

I would recommend to disable deobfuscation by default
to use the safer option by default.

**Comment by erans** [comment]
So you want it to be parsed and return "[]" instead of "@" ? I kinda look
at it more as encoding due to the nature of the field in the Tor network
more than anything else so that when you parse it you want it to return "@"
instead of "[]".

**Comment by nusenu** [comment]
> So you want it to be parsed and return "[]" instead of "@" ?

by default yes, since we don't know how people are going to use the parser
I'd say use the safer option by default.
